#!/usr/bin/env php
<?php

// Setup constants via the command line before loading the configuration
foreach($argv as $arg){
  if(preg_match('/^([^=]+)=([^ ]+)/', $arg, $matches)) define($matches[1], $matches[2]); 
}

define('CLI', false);
define('WEB_REQUEST', true);
define('SERVER_MODE', true);

$_SERVER['SERVER_PORT'] = 3000;
$_SERVER['HTTP_HOST'] = 'localhost';
$_SERVER['REQUEST_URI'] = '/';
$_SERVER['SCRIPT_NAME'] = 'server';

defined('DS')           || define('DS', DIRECTORY_SEPARATOR);
defined('BASE_DIR')  || define('BASE_DIR', str_replace(DS.'script'.DS.'server','',__FILE__));

$_app_config_file = BASE_DIR.DS.'config'.DS.'config.php';

defined('ENVIRONMENT')           || define('ENVIRONMENT', 'development');
include_once(BASE_DIR.DS.'config'.DS.'config.php');

require_once(RAILS_UTILS_DIR.DS.'scripts'.DS.'server.php');

