#!/usr/bin/env php
<?php

defined('DS') || define('DS', DIRECTORY_SEPARATOR);

if (isset($argv[1]) && strstr($argv[1], 'test:')){
    define('ENVIRONMENT', 'testing');
}

if(is_file(dirname(realpath(__FILE__)).DS.'config'.DS.'config.php')){
    include(dirname(realpath(__FILE__)).DS.'config'.DS.'config.php');
}

if(defined('RAILS_DIR')){
    include RAILS_DIR.DS.'rails_utils'.DS.'mrails'.DS.'mrails.php';
}elseif(!is_file(dirname(realpath(__FILE__)).DS.'rails_utils'.DS.'mrails'.DS.'mrails.php') ||
        !include(dirname(realpath(__FILE__)).DS.'rails_utils'.DS.'mrails'.DS.'mrails.php')) {

    if(is_file('vendor'.DS.'rails'.DS.'rails_utils'.DS.'mrails'.DS.'mrails.php')){
        include 'vendor'.DS.'rails'.DS.'rails_utils'.DS.'mrails'.DS.'mrails.php';
    }
}
